CREATE TABLE USER(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    ACCOUNT VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(128) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    ADDRESS VARCHAR(128) NOT NULL,
    PHONE_NO VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    primary key (id)
);